[package]
version = "1.0.0"
title = "Asset validation service"
description = "A simple demonstration of an asset validation microservice."
authors = ["Omniverse Kit Team"]
preview_image = "data/preview_image.png"
readme = "docs/README.md"
changelog = "docs/CHANGELOG.md"
repository = ""
category = "Example"
keywords = ["kit", "service", "asset", "validation", "example"]

[dependencies]
"omni.services.core" = {}
"omni.usd" = {}

# The main Python module this extension provides, it will be publicly available as
# "import omni.services.assets.validate":
[[python.module]]
name = "omni.services.assets.validate"

[settings.exts."omni.services.assets.validate"]
# URL prefix where the validation service will be mounted:
url_prefix = "/assets"
